name: Validate Lua

on:
  push:
    paths:
      - '.github/workflows/lua.yml'
      - '**.lua'
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/lua.yml'
      - '**.lua'
    branches:
      - master

jobs:
  emmylua:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          save-always: true
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install EmmyLua Check
        run: cargo install emmylua_check

      - name: Validate Lua Files
        working-directory: .
        run: emmylua_check . -c .emmyrc.json

  stylua:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v2.3.1
          args: --check --syntax Lua51 .