name: Validate Lua

on:
  push:
    paths:
      - '.github/workflows/lua.yml'
      - '**.lua'
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/lua.yml'
      - '**.lua'
    branches:
      - master

jobs:
  call:
    uses: codyduong/Project-Zomboid-Template/.github/workflows/lint.yml@v0.2.0
